# ==========================================
# [Stage A] 앱 빌드 및 종속성 설치
# ==========================================
FROM node:24-slim AS builder

WORKDIR /data/new_portal_int_api_bill

# Step 1: npm 글로벌 업데이트
RUN npm install -g npm@11.8.0

# Step 2: 의존성 설치 (package*.json만 먼저 복사하여 Docker Layer Cache 활용)
COPY package*.json ./
RUN npm ci --legacy-peer-deps && \
    npm cache clean --force

# Step 3: 소스 코드 및 설정 파일 복사 후 앱 빌드
COPY tsconfig*.json nest-cli.json ./
COPY ./src ./src
COPY ./assets ./assets
RUN npm run build

# Step 4: 프로덕션용 node_modules 정리
RUN npm prune --production --legacy-peer-deps

# ==========================================
# [Stage B] OS 패키지 및 Oracle Client 구성
# ==========================================
FROM node:24-slim AS os-base

ENV TZ=Asia/Seoul \
    DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        tzdata \
        libaio1 \
        wget \
        unzip \
        tcpdump \
        procps \
        net-tools \
        iputils-ping && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    mkdir -p /opt/oracle && \
    cd /opt/oracle && \
    wget --no-check-certificate -q https://download.oracle.com/otn_software/linux/instantclient/214000/instantclient-basic-linux.x64-21.4.0.0.0dbru.zip && \
    unzip instantclient-basic-linux.x64-21.4.0.0.0dbru.zip && \
    rm instantclient-basic-linux.x64-21.4.0.0.0dbru.zip && \
    apt-get purge -y --auto-remove wget unzip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# ==========================================
# [Stage: 3] 최종 이미지 생성
# ==========================================
FROM os-base AS runner

ENV TZ=Asia/Seoul \
    UV_THREADPOOL_SIZE=15 \
    NODE_ENV=development \
    APP_PORT=3000 \
    LD_LIBRARY_PATH=/opt/oracle/instantclient_21_4:$LD_LIBRARY_PATH

WORKDIR /data/new_portal_int_api_bill

# builder 스테이지에서 빌드 결과물 가져오기
COPY --chown=node:node --from=builder /data/new_portal_int_api_bill/package*.json ./
COPY --chown=node:node --from=builder /data/new_portal_int_api_bill/node_modules ./node_modules
COPY --chown=node:node --from=builder /data/new_portal_int_api_bill/dist ./dist
COPY --chown=node:node --from=builder /data/new_portal_int_api_bill/assets ./assets

# logs 디렉터리 생성 및 node 사용자 권한 부여
RUN mkdir -p logs && chown -R node:node /data/new_portal_int_api_bill

USER node

EXPOSE 3000