FROM node:24

# Build Number
ARG BUILD_NUMBER

# Working Directory 설정
WORKDIR /data/ai-app-api

# APP ENV 설정
ENV TZ=Asia/Seoul \
    UV_THREADPOOL_SIZE=15 \
    NODE_ENV=production \
    APP_PORT=3000
    # DD_TRACE_RATE_LIMIT=100 \
    # DD_SERVICE_MAPPING="mysql:prd-town-mysql,redis:prd-town-redis"

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Update npm
RUN npm install -g npm@11.9.0

# MariaDB Client install & Cache Clean
RUN apt-get update && \
    apt-get install -y \
        tcpdump \
        procps \
        net-tools \
        iputils-ping && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# MariaDB 공개 키 등록
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys F1656F24C74CD1D8

# MariaDB APT 저장소 추가 (공식 MariaDB 저장소 사용)
RUN apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'
RUN add-apt-repository 'deb [arch=amd64] http://mirror.leaseweb.com/mariadb/repo/10.11/debian bullseye main'

# MariaDB 설치
RUN apt-get update && apt-get install -y mariadb-server

# 앱 소스 copy
COPY --chown=node:node ./src ./src
COPY --chown=node:node ./assets ./assets
COPY --chown=node:node ./package*.json ./
COPY --chown=node:node ./tsconfig*.json ./
COPY --chown=node:node ./nest-cli.json ./

# COPY ./src ./src
# COPY ./assets ./assets
# COPY ./package*.json ./
# COPY ./tsconfig*.json ./
# COPY ./nest-cli.json ./

# RUN chown -R node:node .

# USER node

RUN npm install --legacy-peer-deps && npm cache clean --force
RUN npm run build
RUN rm -rf src

# devDependencies 라이브러리 삭제(도커 이미지 용량 감량화)
RUN npm prune --production

EXPOSE 3000